### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by XiangZhao969** [ItalianDevs4PM/Towny#1]
[Server] [02:11:53] error> Could not load '/storage/emulated/0/PocketMine/plugins/Towny.phar' in folder '/storage/emulated/0/PocketMine/plugins/': Undefined index: name
[Server] [02:11:53] notice> ArrayOutOfBoundsException: "Undefined index: name" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 65

**Comment by AryToNeX** [comment]
@XiangZhao969 Towny is not complete at all. Sorry.
